"""
Generic script template for Alembic migrations.
Generated by Copilot helper for DocFoundry.
"""
from alembic import op
import sqlalchemy as sa

{{imports if imports else ''}}

def upgrade():
    {{upgrades if upgrades else 'pass'}}


def downgrade():
    {{downgrades if downgrades else 'pass'}}
